// app/layout.jsx
import { Geist, Geist_Mono, Noto_Sans, Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import FooterSection from "./components/FooterSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSans = Noto_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // include the weights you want
  variable: '--font-noto-sans', // optional for custom CSS use
  display: 'swap',
});

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <Header />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}